/******************************************************************************
 * @file Terrain.java
 *
 * @brief Enumeration defining the various types of terrain in Catan.
 *
 * @author glasscock
 *
 * @created Aug 9, 2013
 *****************************************************************************/

package com.zkvj.games.catan;

import java.awt.Color;

public enum Terrain
{
   eMOUNTAIN("Mountain", Resource.eROCK, Constants.kMOUNTAIN_COLOR),
   eFOREST("Forest", Resource.eWOOD, Constants.kFOREST_COLOR),
   eFIELD("Field", Resource.eWHEAT, Constants.kFIELD_COLOR),
   ePASTURE("Pasture", Resource.eSHEEP, Constants.kPASTURE_COLOR),
   eHILLS("Hills", Resource.eBRICK, Constants.kHILLS_COLOR),
   eDESERT("Desert", null, Constants.kDESERT_COLOR);
   
   private static final Terrain[] kValues = Terrain.values();
   private static final int kNUM_VALUES = kValues.length;

   /**
    * Constructor
    * @param aName
    * @param aResource
    * @param aColor
    */
   private Terrain(String aName, Resource aResource, Color aColor)
   {
      this._name = aName;
      this._resourceType = aResource;
      this._color = aColor;
   }
   
   /**
    * Returns the color for this terrain type
    * @return Color
    */
   public Color getColor()
   {
      return _color;
   }

   /**
    * Returns a random Terrain type.
    * @return Terrain
    */
   public static Terrain getRandom()
   {
      return kValues[(int)Math.floor(kNUM_VALUES * Math.random())];
   }

   /**
    * Returns the resource type generated by this terrain type. May be null
    * if the terrain type does not generate resources.
    * @return Resource
    */
   public Resource getResourceType()
   {
      return _resourceType;
   }

   /**
    * Returns a String representation for this resource type.
    * @return String
    */
   @Override
   public String toString()
   {
      return _name;
   }

   private final String _name;
   private final Resource _resourceType;
   private final Color _color;
}