/******************************************************************************
 * @file TerrainHex.java
 *
 * @brief An individual terrain hex on the Catan game board.
 *
 * @author glasscock
 *
 * @created Aug 9, 2013
 *****************************************************************************/

package com.zkvj.games.catan;

public class TerrainHex
{
   /**
    * Constructor
    * @param aType - terrain type for this terrain hex
    */
   public TerrainHex(Terrain aType)
   {
      this._terrainType = aType;
   }

   /**
    * Returns the terrain type for this terrain hex.
    * @return Terrain
    */
   public Terrain getTerrainType()
   {
      return _terrainType;
   }

   /**
    * Returns the resource type generated by this terrain hex. May be null
    * if the terrain type does not generate resources.
    * @return Resource
    */
   public Resource getResourceType()
   {
      return _terrainType.getResourceType();
   }
   
   @Override
   public String toString()
   {
      return _terrainType.toString();
   }

   private final Terrain _terrainType;
}